### ISSUE TITLE
catalina

### ISSUE THREAD

**Issue by 1Wayne1** [sulthonuladib/A455LF-OpenCore#1]
Can this efi be used to catalina?

**Comment by sulthonuladib** [comment]
yes, u need to download the resource first @1Wayne1

**Comment by 1Wayne1** [comment]
> yes, u need to download the resource first @1Wayne1

Thank you for your reply.

I saw the Help.md in OC\Resources and I went to the homepage of Acidanthera. But I don't know which package I should download.

Could you tell me which I should download for OC\Resources, thank you.

**Comment by sulthonuladib** [comment]
@1Wayne1 check acidanthera github. Repo name is OcBinayData

**Comment by sulthonuladib** [comment]
@1Wayne1 there's update for macOS Big Sur public release, u can try :D

**Comment by 1Wayne1** [comment]
> @1Wayne1 there's update for macOS Big Sur public release, u can try :D

Thank U
